### ISSUE TITLE
History page failed to log user IP at demo site

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#209] opened 2018-07-25 16:17 UTC
Is it a common issue?

![6d9613f1-73a6-4de9-b99e-86553237f2e9](https://user-images.githubusercontent.com/4648756/43213418-6f26b888-8feb-11e8-8120-ef6a8d5d0fee.png)

**Comment by BenjaminHae** [comment] 2018-07-25 16:21
Huh that's funny. Haven't seen that before. Maybe there's a reverse proxy involved?
I've not changed the way the ip address is read:

- https://github.com/zeruniverse/Password-Manager/blob/9.15/src/rest/check.php
- https://github.com/zeruniverse/Password-Manager/blob/10.00/src/rest/check.php

@Pofilo can you reproduce this?

**Comment by zeruniverse** [comment] 2018-07-25 16:22
Is this happening at your server?

**Comment by BenjaminHae** [comment] 2018-07-25 16:22
On my server everything looks as it should.
Do you have `phpinfo` available on the system in question? If so could you please check the contents of `$_SERVER['HTTP_X_FORWARDED_FOR']`?

**Comment by Pofilo** [comment] 2018-07-25 16:23
@BenjaminHae, I already experienced that on the demo.
At least one year ago for sure !
I thought it was the configuration + the sourceforge environment ..

History with 10.00 works for me (apache, no special configuration).

**Comment by zeruniverse** [comment] 2018-07-25 16:24
https://phppasswordmanager.sourceforge.io/info.php

**Comment by BenjaminHae** [comment] 2018-07-25 16:25
Yup there's a reverse proxy. I'll fix it.

**Comment by BenjaminHae** [comment] 2018-07-25 16:27
Should be fixed now.

**Closed as completed** 2018-07-26 17:32 UTC
